name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '변경된 기능'
    labels:
      - ':sparkles:'
      - ':lipstick:'
      - ':art:'
      - ':zap:'
      - ':loud_sound:'
      - ':globe_with_meridians:'
      - ':white_check_mark:'
  - title: '수정 버그 내역'
    labels:
      - ':bug:'
      - ':ambulance:'
  - title: '기타'
    labels:
      - ':memo:'
      - ':poop:'
      - ':fire:'
      - ':truck:'
      - ':package:'
      - ':construction_worker:'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
replacers:
  - search: '\[([A-Z]+)-(\d+)\]'
    replace: '[[$1-$2]](https://your-jira-domain.atlassian.net/browse/$1-$2)' # 지라 링크로 변경
exclude-labels:
  - 'skip-changelog' # 변경내역에 포함하지 않을 라벨
include-labelse:
  - ':sparkles:'
  - ':lipstick:'
  - ':art:'
  - ':zap:'
  - ':loud_sound:'
  - ':globe_with_meridians:'
  - ':white_check_mark:'
  - ':bug:'
  - ':ambulance:'
  - ':memo:'
  - ':poop:'
  - ':fire:'
  - ':truck:'
  - ':package:'
  - ':construction_worker:'
version-resolver:
  major:
    labels:
      - 'MAJOR'
  minor:
    labels:
      - 'MINOR'
  patch:
    labels:
      - 'PATCH'
  default: patch
no-changes-template: 이번 릴리즈에는 변경된 내역이 없습니다. 🎉
template: |
  ## 변경내역

  $CHANGES
