name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '변경된 기능'
    labels:
      - '✨'
      - ':sparkles:'
      - '💄'
      - ':lipstick:'
      - '🎨'
      - ':art:'
      - '⚡️'
      - ':zap:'
      - '🔊'
      - ':loud_sound:'
      - '🌐'
      - ':globe_with_meridians:'
      - '✅'
      - ':white_check_mark:'
  - title: '수정 버그 내역'
    labels:
      - '🐛'
      - ':bug:'
      - '🚑️'
      - ':ambulance:'
  - title: '기타'
    labels:
      - '📝'
      - ':memo:'
      - '💩'
      - ':poop:'
      - '🔥'
      - ':fire:'
      - '🚚'
      - ':truck:'
      - '📦'
      - ':package:'
      - '👷'
      - ':construction_worker:'
autolabeler:
  - label: ':art:'
    title:
      - '/🎨/'
      - '/:art:/'
  - label: ':zap:'
    title:
      - '/⚡️/'
      - '/:zap:/'
  - label: ':sparkles:'
    title:
      - '/✨/'
      - '/:sparkles:/'
  - label: ':bug:'
    title:
      - '/🐛/'
      - '/:bug:/'
  - label: ':ambulance:'
    title:
      - '/🚑️/'
      - '/🚑/' # :ambulance: 가 이상하게 잡힐 때도 있음
      - '/:ambulance:/'
  - label: ':loud_sound:'
    title:
      - '/🔊/'
      - '/:loud_sound:/'
  - label: ':lipstick:'
    title:
      - '/:lipstick:/'
      - '/💄/'
  - label: '🌐'
    title:
      - '/🌐/'
      - '/:globe_with_meridians:/'
  - label: '📝'
    title:
      - '/📝/'
      - '/:memo:/'
  - label: '✅'
    title:
      - '/✅/'
      - '/:white_check_mark:/'
  - label: '💩'
    title:
      - '/💩/'
      - '/:poop:/'
  - label: '🔥'
    title:
      - '/🔥/'
      - '/:fire:/'
  - label: '🚚'
    title:
      - '/🚚/'
      - '/:truck:/'
  - label: '📦'
    title:
      - '/📦/'
      - '/:package:/'
  - label: ':construction_worker:'
    title:
      - '/👷/'
      - '/:construction_worker:/'
  - label: 'skip-changelog'
    branch:
      - 'main' # 메인 브랜치에 PR 시, 변경내역에 포함하지 않는다.
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
replacers:
  - search: '\[(\b[A-Z]{2,}-\d+)\]'
    replace: '[[$1]](https://your-jira-domain.atlassian.net/browse/$1)' # 지라 링크로 변경
exclude-labels:
  - 'skip-changelog' # 변경내역에 포함하지 않을 라벨
version-resolver:
  major:
    labels:
      - 'MAJOR'
  minor:
    labels:
      - 'MINOR'
  patch:
    labels:
      - 'PATCH'
  default: patch
no-changes-template: |
  ## 변경내역

  이번 릴리즈에는 변경된 내역이 없습니다. 🎉
template: |
  ## 변경내역

  $CHANGES
