import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <p>NEXT_PUBLIC_API_URL: {process.env.NEXT_PUBLIC_API_URL}</p>
        <p>NEXT_PUBLIC_API_KEY: {process.env.NEXT_PUBLIC_API_KEY}</p>
        <p>MY_ENV: {process.env.MY_ENV}</p>
        <p>MORE_ENV: {process.env.MORE_ENV}</p>
        <p>LOCALE_ENV: {process.env.LOCALE_ENV}</p>
        <p>LANDING_ENV: {process.env.LANDING_ENV}</p>
      </main>
    </>
  );
}
