name: Vercel Main Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Extract PR number from commit message
      - name: Extract PR number
        id: extract_pr_number
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -o -E "#[0-9]+" | tr -d '#')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      # Get PR labels using GitHub API
      - name: Get PR Labels
        id: get_labels
        run: |
          if [ -n "${{ env.PR_NUMBER }}" ]; then
            LABELS=$(gh pr view ${{ env.PR_NUMBER }} --json labels --jq '.labels[].name')
            echo "PR_LABELS=$LABELS" >> $GITHUB_ENV
          else
            echo "No PR number found in commit message."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy Apps if 'deploy-apps' label is present
      - name: Deploy Apps
        if: contains(env.PR_LABELS, 'deploy-apps')
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_APPS }}

      # Deploy Apps-jp if 'deploy-apps-jp' label is present
      - name: Deploy Apps-jp
        if: contains(env.PR_LABELS, 'deploy-apps-jp')
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_APPS_JP }}

      # Deploy Landing if 'deploy-landing' label is present
      - name: Deploy Landing
        if: contains(env.PR_LABELS, 'deploy-landing')
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_LANDING }}

      # Deploy Landing-jp if 'deploy-landing-jp' label is present
      - name: Deploy Landing-jp
        if: contains(env.PR_LABELS, 'deploy-landing-jp')
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_LANDING_JP }}
