name: Labeler for Pull Requests
on:
  pull_request:
    types: [opened]
    branches:
      - main
      - release
      - develop

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
