name: Vercel Main Production Deployment
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  echo:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Apps
        if: contains(github.event.pull_request.labels.*.name, 'deploy-apps')
        run: echo "Deploying to production"
      - name: Deploy Apps-jp
        if: contains(github.event.pull_request.labels.*.name, 'deploy-apps-jp')
        run: echo "Deploying to production-jp"
      - name: Deploy Landing
        if: contains(github.event.pull_request.labels.*.name, 'deploy-landing')
        run: echo "Deploying to production-landing"
      - name: Deploy Landing-jp
        if: contains(github.event.pull_request.labels.*.name, 'deploy-landing-jp')
        run: echo "Deploying to production-landing-jp"
