name: Vercel Main Production Deployment

on:
  push:
    branches:
      - main

jobs:
  check-pr-labels:
    runs-on: ubuntu-latest
    outputs:
      PR_LABELS: ${{ steps.get_labels.outputs.PR_LABELS }}
    steps:
      # Checkout the repository
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main # 이거 ref.main이 아니라 COMMIT으로 바꿔야 deployment에 잘 들어갈듯?
      # Extract PR number from commit message
      - name: Extract PR number
        id: extract_pr_number
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -o -E "#[0-9]+" | head -n 1 | tr -d '#')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "PR_NUMBER=$PR_NUMBER"

      # Get PR labels using GitHub API and sanitize the output
      - name: Get PR Labels
        id: get_labels
        run: |
          if [ -n "${{ steps.extract_pr_number.outputs.PR_NUMBER }}" ]; then
            LABELS=$(gh pr view ${{ steps.extract_pr_number.outputs.PR_NUMBER }} --json labels --jq '.labels[].name' | tr '\n' ',' | sed 's/,$//')
            echo "PR_LABELS=$LABELS" >> $GITHUB_OUTPUT
            echo "PR_LABELS=$LABELS"
          else
            echo "No PR number found in commit message."
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-apps:
    # Deploy Apps if 'deploy-apps' label is present
    runs-on: ubuntu-latest
    needs: check-pr-labels
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Deploy Apps
        if: contains(needs.check-pr-labels.outputs.PR_LABELS, 'deploy-apps')
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_APPS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRODUCTION: true
          GITHUB_DEPLOYMENT_ENV: Production - monorepo-version-control-apps
          BUILD_ENV: |
            NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}

  deploy-apps-jp:
    # Deploy Apps-jp if 'deploy-apps-jp' label is present
    runs-on: ubuntu-latest
    needs: check-pr-labels
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Deploy Apps-jp
        if: contains(needs.check-pr-labels.outputs.PR_LABELS, 'deploy-apps-jp')
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_APPS_JP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRODUCTION: true
          GITHUB_DEPLOYMENT_ENV: Production - monorepo-version-control-apps-jp
          BUILD_ENV: |
            NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}
            VERCEL_PUBLIC_API_URL=yamlwins

  deploy-landing:
    # Deploy Landing if 'deploy-landing' label is present
    runs-on: ubuntu-latest
    needs: check-pr-labels
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Deploy Landing
        if: contains(needs.check-pr-labels.outputs.PR_LABELS, 'deploy-landing')
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LANDING }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRODUCTION: true
          GITHUB_DEPLOYMENT_ENV: Production - monorepo-version-control-landing

  deploy-landing-jp:
    # Deploy Landing-jp if 'deploy-landing-jp' label is present
    runs-on: ubuntu-latest
    needs: check-pr-labels
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Deploy Landing-jp
        if: contains(needs.check-pr-labels.outputs.PR_LABELS, 'deploy-landing-jp')
        uses: BetaHuhn/deploy-to-vercel-action@latest
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LANDING_JP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRODUCTION: true
          GITHUB_DEPLOYMENT_ENV: Production - monorepo-version-control-landing-jp
