name: Vercel Main Production Deployment

on:
  push:
    branches:
      - main

jobs:
  check-pr-labels:
    runs-on: ubuntu-latest
    outputs:
      PR_LABELS: ${{ steps.get_labels.outputs.PR_LABELS }}
    steps:
      # Checkout the repository
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      # Extract PR number from commit message
      - name: Extract PR number
        id: extract_pr_number
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -o -E "#[0-9]+" | head -n 1 | tr -d '#')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "PR_NUMBER=$PR_NUMBER"

      # Get PR labels using GitHub API and sanitize the output
      - name: Get PR Labels
        id: get_labels
        run: |
          if [ -n "${{ steps.extract_pr_number.outputs.PR_NUMBER }}" ]; then
            LABELS=$(gh pr view ${{ steps.extract_pr_number.outputs.PR_NUMBER }} --json labels --jq '.labels[].name' | tr '\n' ',' | sed 's/,$//')
            echo "PR_LABELS=$LABELS" >> $GITHUB_OUTPUT
            echo "PR_LABELS=$LABELS"
          else
            echo "No PR number found in commit message."
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-apps:
    #
    # Deploy Apps if 'deploy-apps' label is present
    runs-on: ubuntu-latest
    needs: check-pr-labels
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Apps
        if: contains(needs.check-pr-labels.outputs.PR_LABELS, 'deploy-apps')
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_APPS }}

  deploy-apps-jp:
    #
    # Deploy Apps-jp if 'deploy-apps-jp' label is present
    runs-on: ubuntu-latest
    needs: check-pr-labels
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Apps-jp
        if: contains(needs.check-pr-labels.outputs.PR_LABELS, 'deploy-apps-jp')
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_APPS_JP }}

  deploy-landing:
    #
    # Deploy Landing if 'deploy-landing' label is present
    runs-on: ubuntu-latest
    needs: check-pr-labels
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Landing
        if: contains(needs.check-pr-labels.outputs.PR_LABELS, 'deploy-landing')
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_LANDING }}

  deploy-landing-jp:
    #
    # Deploy Landing-jp if 'deploy-landing-jp' label is present
    runs-on: ubuntu-latest
    needs: check-pr-labels
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Landing-jp
        if: contains(needs.check-pr-labels.outputs.PR_LABELS, 'deploy-landing-jp')
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_LANDING_JP }}
