name: Vercel Main Production Deployment
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  deploy-vercel:
    # IF PR merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout the main branch (always deploy from main after merge)
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Deploy to Vercel
      - name: Deploy Apps
        if: contains(github.event.pull_request.labels.*.name, 'deploy-apps')
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_APPS }}
      - name: Deploy Apps-jp
        if: contains(github.event.pull_request.labels.*.name, 'deploy-apps-jp')
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_APPS_JP }}
      - name: Deploy Landing
        if: contains(github.event.pull_request.labels.*.name, 'deploy-landing')
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_LANDING }}
      - name: Deploy Landing-jp
        if: contains(github.event.pull_request.labels.*.name, 'deploy-landing-jp')
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_LANDING_JP }}
