name: Vercel Main Production Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-apps:
    # PR이 Merge 되고, deploy-app 라벨이 붙어있을 때만 동작한다.
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy-app')
    runs-on: ubuntu-latest
    environment: Production – monorepo-version-control-apps
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Deploy Apps
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_APPS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DEPLOYMENT: false
          PRODUCTION: true
          BUILD_ENV: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}
            NEXT_PUBLIC_NODE_ENV=${{ secrets.NEXT_PUBLIC_NODE_ENV }}

  deploy-apps-jp:
    # PR이 Merge 되고, deploy-app-jp 라벨이 붙어있을 때만 동작한다.
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy-app-jp')
    runs-on: ubuntu-latest
    environment: Production – monorepo-version-control-apps-jp
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Deploy Apps-jp
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_APPS_JP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DEPLOYMENT: false
          PRODUCTION: true
          BUILD_ENV: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}
            NEXT_PUBLIC_NODE_ENV=${{ secrets.NEXT_PUBLIC_NODE_ENV }}

  deploy-landing:
    # PR이 Merge 되고, deploy-landing 라벨이 붙어있을 때만 동작한다.
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy-landing')
    runs-on: ubuntu-latest
    environment: Production – monorepo-version-control-landing
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Deploy Landing
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LANDING }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DEPLOYMENT: false
          PRODUCTION: true
          BUILD_ENV: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}
            NEXT_PUBLIC_NODE_ENV=${{ secrets.NEXT_PUBLIC_NODE_ENV }}

  deploy-landing-jp:
    # PR이 Merge 되고, deploy-landing-jp 라벨이 붙어있을 때만 동작한다.
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy-landing-jp')
    runs-on: ubuntu-latest
    environment: Production – monorepo-version-control-landing-jp
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Deploy Landing-jp
        uses: BetaHuhn/deploy-to-vercel-action@latest
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LANDING_JP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DEPLOYMENT: false
          PRODUCTION: true
          BUILD_ENV: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}
            NEXT_PUBLIC_NODE_ENV=${{ secrets.NEXT_PUBLIC_NODE_ENV }}
