# Release Branch에 push가 발생하면 Release Draft를 작성
name: Release Drafter

on:
  push:
    branches: 'release'

permissions:
  contents: read
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
