# 버전관리를 위한 라벨링 자동화
name: Labeling for Release Drafter

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  label_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: '.github/release-drafter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
