# 버전관리를 위한 라벨링 자동화
name: Labeling for Release Drafter

on:
  pull_request:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  label_release_draft:
    if: github.event.pull_request.base.ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: 'release-drafter.yml'
