# Release Branch에 push가 발생하면 Release Draft를 작성
name: Release Drafter

on:
  pull_request:
    branches: ['release']
    types: [closed]

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: 'drafter-release.yml'
